package com.ferncircle.string;

/**
 * 
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 * @author dbrit00s
 *
 */
public class FindDifference {


	public char findTheDifference(String s, String t) {
		
		int[] chars = new int[26];
		char[] sArr = s.toCharArray();
		char[] tArr = t.toCharArray();
		
		for(int i=0; i< s.length(); i++){
			int index = sArr[i] - 97;
			chars[index]++;
		}
		
		for(int i=0; i< t.length(); i++){
			int index = tArr[i] -97;
			if(chars[index] == 0){
				char result = (char)(index + 97);
				return result;
			}
			
			chars[index]--;
		}
		return 0;
	}
	
	public static void main(String[] args) {
		
		FindDifference fd = new FindDifference();
		System.out.println(fd.findTheDifference("aaa", "aaa"));

	}

}
